version: '3.8'

services:
  roadrunner:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: test_app
    volumes:
      - ./src:/app
    ports:
      - "8000:8000"
      - "6001:6001"